algo_name: td3
env_name: HalfCheetah
seed: 6782

nenvs: 4
nsize: 50000
minibatch: 256
start_noise: 0.5
end_noise: 0.01
training_frequency: 1
tau: 0.01
actor_lr_rate: 0.001
actor_update_decay: 3
critic_lr_rate: 0.001
save_model_frequency: 10000
start_training_size: 10000
train_steps: 250000
evaluate_steps: 10000
gamma: 0.99
logger: wandb
logdir: "./logs/"
modeldir: "./models/"