algo_name: ddpg
env_name: Walker2d
seed: 19089

nenvs: 4
nsize: 50000
minibatch: 256
start_noise: 1.0
end_noise: 0.01
training_frequency: 1
tau: 0.01
actor_lr_rate: 0.001
critic_lr_rate: 0.001
save_model_frequency: 10000
start_training_size: 10000
train_steps: 250000
evaluate_steps: 10000
gamma: 0.99
logger: tensorboard
logdir: "./logs/"
modeldir: "./models/"