algo_name: ppo
env_name: HalfCheetah

nenvs: 16
nsize: 256
nminibatch: 8
nepoch: 16

vf_coef: 0.25
ent_coef: 0.00
clipgrad_norm: 0.5
clip_range: 0.20
target_kl: 0.01
lr_rate: 0.0004

save_model_frequency: 1000
train_steps: 62500
evaluate_steps: 10000

gamma: 0.99
tdlam: 0.95

logger: wandb # or tensorboard
logdir: "./logs/"
modeldir: "./models/"