algo_name: ppo
env_name: walkerStand0608
seed: 79811

nenvs: 16
nsize: 256
nminibatch: 8
nepoch: 16

mlp_hiddens: 128, 128

vf_coef: 0.25
ent_coef: 0.00
clipgrad_norm: 0.5
clip_range: 0.20
target_kl: 0.03
lr_rate: 0.0007

save_model_frequency: 1000
train_steps: 750000
evaluate_steps: 10000

gamma: 0.98
tdlam: 0.95

logger: tensorboard # or wandb | tensorboard
logdir: "logs/"
modeldir: "models/"