algo_name: double-dqn
env_name: Pong
seed: 1069

nenvs: 4
nsize: 25000
minibatch: 256
start_egreedy: 0.5
end_egreedy: 0.1
training_frequency: 4
update_frequency: 25
lr_rate: 0.001
save_model_frequency: 100
start_training_size: 1000
train_steps: 25000
evaluate_steps: 500
gamma: 0.99
logdir: "./logs/"
modeldir: "./models/"