algo_name: a2c
env_name: HalfCheetah

nenvs: 16
nsize: 32
nminibatch: 1
nepoch: 1

vf_coef: 0.25
ent_coef: 0.00
clipgrad_norm: 0.5
lr_rate: 0.001

save_model_frequency: 100
train_steps: 62500
evaluate_steps: 10000

gamma: 0.99
tdlam: 0.95

logger: wandb # or tensorboard
logdir: "./logs/"
modeldir: "./models/"