nenvs: 16
nsize: 64
nminibatch: 1
nepoch: 1

vf_coef: 0.25
ent_coef: 0.00
clipgrad_norm: 0.5
lr_rate: 0.0007

save_model_frequency: 100
train_steps: 62500
evaluate_steps: 10000

gamma: 0.99
tdlam: 0.95

logdir: "./logs/Ant/a2c/" 
modeldir: "./models/Ant/a2c/"