name: dqn
nenvs: 8  
nsize: 10000
minibatch: 128
start_egreedy: 0.5
end_egreedy: 0.05
training_frequency: 1
update_frequency: 500
lr_rate: 0.00025
save_model_frequency: 5000
start_training_size: 10000
train_steps: 1250000
evaluate_steps: 10000
gamma: 0.99
logdir: "./logs/PongNoFrameskip-v4/dqn/"
modeldir: "./models/PongNoFrameskip-v4/dqn/"